### ISSUE TITLE
 TensorType does not support iteration.

### ISSUE THREAD

**Issue by anchavesb** [baidu-research/ba-dls-deepspeech#16]
Hi, I'm trying to run train.py but got the following error:

```
/usr/bin/python2.7 train.py train_corpus.json validation_corpus.json model
Using Theano backend.
/usr/local/lib/python2.7/dist-packages/Theano-0.8.2-py2.7.egg/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
2017-01-14 09:01:03,510 INFO    (data_generator) Reading description file: train_corpus.json for partition: train
2017-01-14 09:01:04,248 INFO    (data_generator) Reading description file: validation_corpus.json for partition: validation
2017-01-14 09:01:05,246 INFO    (model) Building gru model
/usr/local/lib/python2.7/dist-packages/Keras-1.2.0-py2.7.egg/keras/engine/topology.py:368: UserWarning: The `regularizers` property of layers/models is deprecated. Regularization losses are now managed via the `losses` layer/model property.
  warnings.warn('The `regularizers` property of '
2017-01-14 09:01:09,422 INFO    (model) Building train_fn
Traceback (most recent call last):
  File "train.py", line 155, in <module>
    args.sortagrad)
  File "train.py", line 126, in main
    train_fn = compile_train_fn(model)
  File "/home/achaves/temp/deepspeech/ba-dls-deepspeech/model.py", line 51, in compile_train_fn
    updates=updates)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.2.0-py2.7.egg/keras/backend/theano_backend.py", line 929, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.2.0-py2.7.egg/keras/backend/theano_backend.py", line 908, in __init__
    for v, nv in updates:
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.8.2-py2.7.egg/theano/tensor/var.py", line 553, in __iter__
    raise TypeError(('TensorType does not support iteration. '
TypeError: TensorType does not support iteration. Maybe you are using builtin.sum instead of theano.tensor.sum? (Maybe .max?)
```

Any ideas? Thanks in advance

**Comment by srvinay** [comment]
Can you try running this with Theano:0.8.2 and Keras:1.1.0?

**Comment by EgorLakomkin** [comment]
I have substituted optimizer from Lasagne to SGD from Keras and it worked

**Comment by anchavesb** [comment]
I downgraded to Keras:1.1.0 and that solved the issue.

Thank you!
