### ISSUE TITLE
the shapes are incompatible

### ISSUE THREAD

**Issue by olesyaksyon** [baidu-research/ba-dls-deepspeech#41]
Hi

I am trying to train my own model, but receive the mistake:

Traceback (most recent call last):
  File "train.py", line 155, in <module>
    args.sortagrad)
  File "train.py", line 123, in main
    model = compile_gru_model(recur_layers=3, nodes=1000, batch_norm=True)
  File "/home/SPEECH/deepspeech2/ba-dls-deepspeech/model.py", line 118, in compile_gru_model
    return_sequences=True)(output)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 491, in __call__
    self.build(input_shapes[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 502, in build
    self.W = K.concatenate([self.W_z, self.W_r, self.W_h])
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 753, in concatenate
    return tf.concat(axis, [to_dense(x) for x in tensors])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1122, in concat
    tensor_shape.scalar())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 848, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (3, 1000, 1000) and () are incompatible

**Comment by olesyaksyon** [comment]
my mistake was in using Tesnorflow in place of Theano
